version: "3"
services:
  web:
    build: .
    restart: always
    networks:
      webapp:
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./images:/app/images
  mysql:
    build: ./sql
    container_name: godockerDB
    restart: always
    networks:
      webapp:
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  nginx:
    image: nginx
    container_name: test-nginx
    restart: always
    networks:
      webapp:
    ports:
      - "80:80"
    volumes:
      - ./vue/user/:/usr/share/nginx/html/user/
      - ./Nodejs/aimc-llm/dist:/usr/share/nginx/html/admin/
      - ./vue/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  mongodb:
    image: mongo
    container_name: mymongo
    restart: always
    networks:
      webapp:
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
  nodejs:
    build: ./Nodejs/aimc-node
    container_name: mynodejs
    restart: always
    networks:
      webapp:
    depends_on:
      - mongodb
    volumes:
      - ./Nodejs/aimc-node:/usr/src/app
    ports:
      - "3000:3000"

networks:
  webapp:
    driver: bridge
volumes:
  mysql-data:
    driver: local
  mongo-data:
    driver: local