version: "3"
services:
  web:
    build: .
    restart: always
    networks:
      webapp:
    ports:
      - "8080:8080"
    depends_on:
      - mysql
#    volumes:
#      - ./images:/app/images
  mysql:
    build: ./sql
    container_name: godockerDB
    restart: always
    networks:
      webapp:
    ports:
      - "3307:3306"
#    volumes:
#      - ~/route_planner/mysql/data:var/lib/mysql
#  nginx:
#    image: nginx
#    restart: always
#    networks:
#      webapp:
#    ports:
#      - "80:80"
#    volumes:
#      - ~/route_planner/nginx/html/:/usr/share/nginx/html/
#      - ~/route_planner/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
#      - ~/route_planner/nginx/conf/nginx_gzip.conf:/etc/nginx/nginx_gzip.conf
#      - ~/route_planner/images/:/usr/share/nginx/images/
#    privileged: true
networks:
  webapp:
    driver: bridge