server:
  host: "0.0.0.0"
  port: 8080
  imagePath: "./"
  imageBaseUrl: "http://localhost:8080"
mysql:
  dataSourceName: "root:root@(localhost:3306)/route-planner?charset=utf8mb4&parseTime=true&loc=Local"
  maxOpenConns: 20     # 连接池最大连接数
  maxIdleConns: 10     # 连接池最大空闲连接数