server:
  host: "0.0.0.0"
  port: 8080
  imagePath: "./"
  imageBaseUrl: "http://localhost:8080"
  WebIP: "20.89.130.136"
#  WebIP: "localhost"

mysql:
  dataSourceName: "root:root@tcp(godockerDB:3306)/route_planner?charset=utf8mb4&parseTime=true&loc=Local"
#  dataSourceName: "root:root@tcp(localhost:3306)/route_planner?charset=utf8mb4&parseTime=true&loc=Local"
  maxOpenConns: 20     # 连接池最大连接数
  maxIdleConns: 10     # 连接池最大空闲连接数h
node_config:
  node_prefix: "mynodejs:3000"